### ISSUE TITLE
Separators in values

### ISSUE THREAD

**Issue by eush77** [sindresorhus/parse-columns#6]
Input:

```
$ ps -p 29920 -o cmd,pid,start
CMD                           PID  STARTED
emacs -nw .                 29920   Oct 16
```

Output:

``` js
[ { CMD: 'emacs', '': '.', PID: '29920', STARTED: 'Oct 16' } ]
```

Expected output:

``` js
[ { CMD: 'emacs -nw .', PID: '29920', STARTED: 'Oct 16' } ]
```

Apparently the algorithm is not working in this case (column split is wrong, and also `-nw` is missing), I wonder if there is a simple fix.

---

One idea is to split not based on vertically aligned separators (as it may be just a coincidence), but instead on header positions. Say, for the example above we could take an `indexOf` for each header:

| header | index |
| --- | --- |
| CMD | 0 |
| PID | 30 |
| STARTED | 35 |

And then for each line we could adjust these positions like this:

``` js
while (!reSeparator.test(line[pos - 1]) {
  pos -= 1;
}
```

And then just `slice` that row and `trim` the values.

This approach, if implemented, would parse the example above and pass the tests (I think), but it would fail in other cases where header is right-aligned, and the value contains separators, such as:

```
        CMD                   PID  STARTED
emacs -nw .                 29920   Oct 16
```

However, I didn't manage to come up with an example using `ps(1)`. Maybe you know tools that output data in such format (apart from Node apps using `text-table` and right align — but these hopefully provide an API and you wouldn't parse their output anyway).

Another trap is headers containing separators (such as `Mounted on` from the readme), but we could use the existing algorithm to detect such headers (and this is in fact all we can do).

**Comment by sindresorhus** [comment]
Yeah, I think a combination of the current algorithm and also taking headers into consideration would work. Headers can be multiple words, true, but those words are separated by one space, while headers themselves are always (?) separated by at least two spaces, eg. `PID  STARTED`.

Would you be interested in doing a pull request?

**Comment by eush77** [comment]
@sindresorhus Totally! I will try to hack on this this week.

> Headers can be multiple words, true, but those words are separated by one space, while headers themselves are always (?) separated by at least two spaces, eg. `PID STARTED`.

This isn't always the case, unfortunately:

```
$ ps -C cat -o pid,command
  PID COMMAND
  586 cat
  587 cat
 2124 /bin/cat
13608 cat
16205 cat
25415 cat
```

**Comment by sindresorhus** [comment]
Then I guess we'll just require the user to define the headers upfront in that case.

**Comment by eush77** [comment]
Or we could continue to use the current algorithm for headers:

```
$ ps -C cat -o pid,command |parse-columns |jq
[
  {
    "PID": "586",
    "COMMAND": "cat"
  },
  {
    "PID": "587",
    "COMMAND": "cat"
  },
  {
    "PID": "2124",
    "COMMAND": "/bin/cat"
  },
  {
    "PID": "16205",
    "COMMAND": "cat"
  },
  {
    "PID": "25415",
    "COMMAND": "cat"
  }
]
```

But maybe that's a bad idea. I'm unsure.

**Comment by sindresorhus** [comment]
:+1:
