### ISSUE TITLE
Typings for typescript

### ISSUE THREAD

**Issue by int0h** [sindresorhus/parse-columns#8]
What do you think about adding some typings for typescript developers? 

(They are type annotations, which provide better type checking if you use typescript)

I've made a fork of your repo https://github.com/int0h/parse-columns and can create a pull request to yours if you are interested.

**Comment by sindresorhus** [comment]
I'm not using TypeScript personally, so I'm not interested or able to maintain type definitions for it. Would be better to submit to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead.

See: https://github.com/sindresorhus/ama/issues/439

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
